### PR TITLE
Use the flake8 CLI

### LINKED ISSUE #5: Doesn't respect `max-line-length`
The `max-line-length` config value seems to be ignored. There's a [suggestion](http://stackoverflow.com/questions/28436382/flake8-not-picking-up-config-file) that this was a regression with a previous version of pep8, however testing the latest version locally did not fix the problem.

### PR DESCRIPTION
**Pull request by nickstenning**
Hi folks!

Following up on a conversation we had quite a while ago about https://github.com/houndci/python/issues/5, I've put together this changeset which changes the Python checker to use the flake8 CLI rather than its library interface.

This fixes #5 (and presumably a number of related but unreported issues) and also upgrades to the latest version of flake8, which has broken the library interface used by the current checker code. It is naturally a bit slower than the previous checker, but hopefully it's still fast enough.

I'd love to get your feedback on whether this is something we could get shipped with Hound, as it would allow me to turn on Hound for a number of python projects. One thing in particular I'd like some feedback on is how to handle unexpected errors. Should the code communicate in any particular way back to the queue? Should it attempt to catch and recover from any errors while running the check?

Thanks for taking a look!

### CODE REVIEW

**Comment by nickstenning** [comment]
Any thoughts @thorncp before we head into the weekend when I'll have some time to address any issues you might raise?

**Comment by gylaz** [comment]
> One thing in particular I'd like some feedback on is how to handle unexpected errors. Should the code communicate in any particular way back to the queue? Should it attempt to catch and recover from any errors while running the check?

We don't currently have a great way to handle this. Ideally, we'd report an error as a violation on either the file that caused it, or no file at all, and put that on the queue.

**Comment by nickstenning** [comment]
Is there anything more I can do to help here? Do you need some benchmarks to see the speed differences between this and the previous version? It would be great to try this out on the production Hound service if we can.

**Comment by gylaz** [comment]
Did a sanity test on staging -- looked good. Merged and deployed to production.

Thanks @nickstenning! Let us know how it works out for you.

**Comment by nickstenning** [comment]
Yay! Thanks @gylaz, thanks all!

**Pull request merged**
